root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/antholume ."
full_bin = "./tmp/antholume serve"
delay = 1000
include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "yaml", "yml"]
exclude_dir = ["_scratch", "build", "data", "frontend", "node_modules"]
exclude_file = ["assets/style.css"]
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
