kind: pipeline
type: kubernetes
name: default

steps:
  # Unit Tests
  - name: unit test
    image: golang
    commands:
      - make tests_unit

  # Integration Tests (Every Month)
  - name: integration test
    image: golang
    commands:
      - make tests_integration
    when:
      event:
        - cron
      cron:
        - integration-test

  # Fetch tags
  - name: fetch tags
    image: alpine/git
    commands:
      - git fetch --tags

  # Publish docker image
  - name: publish docker
    image: plugins/docker
    settings:
      repo: gitea.va.reichard.io/evan/antholume
      registry: gitea.va.reichard.io
      tags:
        - dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
