// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package database

import (
	"time"
)

type Activity struct {
	ID          int64     `json:"id"`
	UserID      string    `json:"user_id"`
	DocumentID  string    `json:"document_id"`
	DeviceID    string    `json:"device_id"`
	StartTime   time.Time `json:"start_time"`
	Duration    int64     `json:"duration"`
	CurrentPage int64     `json:"current_page"`
	TotalPages  int64     `json:"total_pages"`
	CreatedAt   time.Time `json:"created_at"`
}

type Device struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	DeviceName string    `json:"device_name"`
	CreatedAt  time.Time `json:"created_at"`
	Sync       bool      `json:"sync"`
}

type Document struct {
	ID          string    `json:"id"`
	Md5         *string   `json:"md5"`
	Filepath    *string   `json:"filepath"`
	Title       *string   `json:"title"`
	Author      *string   `json:"author"`
	Series      *string   `json:"series"`
	SeriesIndex *int64    `json:"series_index"`
	Lang        *string   `json:"lang"`
	Description *string   `json:"description"`
	Olid        *string   `json:"-"`
	Synced      bool      `json:"-"`
	Deleted     bool      `json:"-"`
	UpdatedAt   time.Time `json:"updated_at"`
	CreatedAt   time.Time `json:"created_at"`
}

type DocumentDeviceSync struct {
	UserID     string    `json:"user_id"`
	DocumentID string    `json:"document_id"`
	DeviceID   string    `json:"device_id"`
	LastSynced time.Time `json:"last_synced"`
	Sync       bool      `json:"sync"`
}

type DocumentProgress struct {
	UserID     string    `json:"user_id"`
	DocumentID string    `json:"document_id"`
	DeviceID   string    `json:"device_id"`
	Percentage float64   `json:"percentage"`
	Progress   string    `json:"progress"`
	CreatedAt  time.Time `json:"created_at"`
}

type RescaledActivity struct {
	DocumentID string    `json:"document_id"`
	DeviceID   string    `json:"device_id"`
	UserID     string    `json:"user_id"`
	StartTime  time.Time `json:"start_time"`
	Page       int64     `json:"page"`
	Duration   int64     `json:"duration"`
}

type User struct {
	ID        string    `json:"id"`
	Pass      string    `json:"-"`
	Admin     bool      `json:"-"`
	CreatedAt time.Time `json:"created_at"`
}
